//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMarniLopezLopez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prd_master()
        {
            this.srv_detail = new HashSet<srv_detail>();
        }
    
        public int prd_id { get; set; }
        public string prd_shdsc { get; set; }
        public string prd_lgdsc { get; set; }
        public decimal prd_price { get; set; }
        public int cat_id { get; set; }
        public int sts_id { get; set; }
    
        public virtual cat_master cat_master { get; set; }
        public virtual sts_master sts_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<srv_detail> srv_detail { get; set; }
    }
}
