//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMarniLopezLopez.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class srv_detail
    {
        [Display(Name = "Id")]
        public int srv_id { get; set; }
        [Display(Name = "Cantidad")]
        public int srv_qty { get; set; }
        [Display(Name = "Notas")]
        public string srv_notes { get; set; }
        [Display(Name = "Producto No")]
        public int prd_id { get; set; }
        [Display(Name = "Detalle No")]
        public int srv_dtl_id { get; set; }
    
        public virtual prd_master prd_master { get; set; }
        public virtual srv_master srv_master { get; set; }
    }
}
