//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMarniLopezLopez.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usr_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usr_master()
        {
            this.srv_master = new HashSet<srv_master>();
        }
        [Display(Name = "ID del Usuario")]
        public string usr_id { get; set; }
        [Display(Name = "Password del usuario")]
        public string usr_password { get; set; }
        [Display(Name = "ID del Estado")]
        public int sts_id { get; set; }
        [Display(Name = "ID del Rol")]
        public int rol_id { get; set; }
    
        public virtual rol_master rol_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<srv_master> srv_master { get; set; }
        public virtual sts_master sts_master { get; set; }
    }
}
