//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2MarniLopez.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class desayuno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public desayuno()
        {
            this.ordenDesayunoes = new HashSet<ordenDesayuno>();
        }
        [Display(Name = "Id Tipo Desayuno")]
        public int idDesayuno { get; set; }
        [Display(Name = "Tipo Desayuno")]
        public string nombre { get; set; }
        [Display(Name = "Tipo Descripcion")]
        public string descripcion { get; set; }
        public Nullable<decimal> precio8 { get; set; }
        public Nullable<decimal> precio9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenDesayuno> ordenDesayunoes { get; set; }
    }
}
