//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2MarniLopez.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ordenDesayuno
    {
        [Display(Name = "Id Orden")]
        public int idOrdenDesayuno { get; set; }
        [Display(Name = "Nombre Cliente")]
        public string nombre { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }
        [Display(Name = "TipoDesayuno")]
        public Nullable<int> idDesayuno { get; set; }
        [Display(Name = "Tamaño")]
        public Nullable<int> tamano { get; set; }
        [Display(Name = "Total")]
        public Nullable<decimal> total { get; set; }
        [Display(Name = "Cantidad")]
        public Nullable<int> cantidad { get; set; }
    
        public virtual desayuno desayuno { get; set; }
    }
}
