//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMarniLopezLopez.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prj_marnylopezEntities1 : DbContext
    {
        public prj_marnylopezEntities1()
            : base("name=prj_marnylopezEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_master> cat_master { get; set; }
        public virtual DbSet<dtb_master> dtb_master { get; set; }
        public virtual DbSet<pay_master> pay_master { get; set; }
        public virtual DbSet<prd_master> prd_master { get; set; }
        public virtual DbSet<rol_master> rol_master { get; set; }
        public virtual DbSet<srv_master> srv_master { get; set; }
        public virtual DbSet<sts_master> sts_master { get; set; }
        public virtual DbSet<usr_master> usr_master { get; set; }
        public virtual DbSet<srv_detail> srv_detail { get; set; }
    }
}
